ALTER TABLE "quote_line_items"
  ADD COLUMN IF NOT EXISTS "line_key" text,
  ADD COLUMN IF NOT EXISTS "bom_rule_id" text,
  ADD COLUMN IF NOT EXISTS "is_manual_quantity" boolean;--> statement-breakpoint
ALTER TABLE "trade_templates"
  ADD COLUMN IF NOT EXISTS "engine_version" integer,
  ADD COLUMN IF NOT EXISTS "template_revision" integer,
  ADD COLUMN IF NOT EXISTS "parameter_definitions" jsonb,
  ADD COLUMN IF NOT EXISTS "bom_rules" jsonb;--> statement-breakpoint
DROP INDEX IF EXISTS "trade_templates_trade_type_slug_uidx";--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "trade_templates_trade_type_slug_revision_uidx"
  ON "trade_templates" USING btree ("trade_type", "slug", "template_revision");--> statement-breakpoint

INSERT INTO "trade_templates"
  ("trade_type", "name", "slug", "default_line_items", "engine_version", "template_revision", "parameter_definitions", "bom_rules")
VALUES
(
  'Cabinetmaker / Joinery', 'Kitchens / Custom', 'kitchens-custom',
  '[{"lineKey":"melamine","description":"Melamine carcasses and fronts","category":"sheet-material","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"hinges","description":"Cabinet hinges","category":"hardware","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"runners","description":"Drawer runners","category":"hardware","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"benchtop","description":"Benchtop","category":"benchtop","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false}]',
  1, 1,
  '[{"id":"totalCabinetRunM","label":"Total cabinet run","unit":"m","defaultValue":3,"minimum":0,"step":0.1},{"id":"baseCabinetHeightMm","label":"Base cabinet height","unit":"mm","defaultValue":900,"minimum":0,"step":10},{"id":"overheadCabinetHeightMm","label":"Overhead cabinet height","unit":"mm","defaultValue":700,"minimum":0,"step":10},{"id":"benchtopDepthMm","label":"Benchtop depth","unit":"mm","defaultValue":600,"minimum":0,"step":10},{"id":"drawerBankCount","label":"Drawer bank count","unit":"qty","defaultValue":1,"minimum":0,"step":1},{"id":"doorCount","label":"Door count","unit":"qty","defaultValue":6,"minimum":0,"step":1}]',
  '[{"lineKey":"melamine","bomRuleId":"cabinet_melamine_area"},{"lineKey":"hinges","bomRuleId":"cabinet_hinges"},{"lineKey":"runners","bomRuleId":"cabinet_runners"},{"lineKey":"benchtop","bomRuleId":"cabinet_benchtop_area"}]'
),
(
  'Carpenter / Joiner', 'Decks / Subframes', 'decks-subframes',
  '[{"lineKey":"decking","description":"Decking boards","category":"decking","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"joists","description":"Joists","category":"structural-timber","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"bearers","description":"Bearers","category":"structural-timber","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"posts","description":"Posts / stumps","category":"structural-timber","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true}]',
  1, 1,
  '[{"id":"lengthM","label":"Deck length","unit":"m","defaultValue":5,"minimum":0,"step":0.1},{"id":"widthM","label":"Deck width","unit":"m","defaultValue":4,"minimum":0,"step":0.1},{"id":"elevationMm","label":"Elevation from ground","unit":"mm","defaultValue":600,"minimum":0,"step":10},{"id":"joistSpacingMm","label":"Joist spacing","unit":"mm","defaultValue":450,"minimum":0,"step":10},{"id":"bearerSpanMm","label":"Bearer span","unit":"mm","defaultValue":1800,"minimum":0,"step":10},{"id":"boardWidthMm","label":"Board width","unit":"mm","defaultValue":90,"minimum":0,"step":1}]',
  '[{"lineKey":"decking","bomRuleId":"decking_linear_metres"},{"lineKey":"joists","bomRuleId":"deck_joists_linear_metres"},{"lineKey":"bearers","bomRuleId":"deck_bearers_linear_metres"},{"lineKey":"posts","bomRuleId":"deck_posts"}]'
),
(
  'Concreter', 'Slabs / Footings', 'slabs-footings',
  '[{"lineKey":"concrete","description":"Ready-mix concrete","category":"concrete","quantity":1,"unit":"cubic metre","unitType":"m3","unitCost":0,"markupPercentage":18,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"trenchMesh","description":"Trench mesh","category":"reinforcement","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"slabMesh","description":"Slab mesh","category":"reinforcement","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"barChairs","description":"Bar chair boxes","category":"reinforcement","quantity":1,"unit":"box","unitType":"box","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true}]',
  1, 1,
  '[{"id":"lengthM","label":"Length","unit":"m","defaultValue":5,"minimum":0,"step":0.1},{"id":"widthM","label":"Width","unit":"m","defaultValue":4,"minimum":0,"step":0.1},{"id":"slabThicknessMm","label":"Slab thickness","unit":"mm","defaultValue":100,"minimum":0,"step":10},{"id":"edgeBeamDepthMm","label":"Edge beam depth","unit":"mm","defaultValue":300,"minimum":0,"step":10},{"id":"edgeBeamWidthMm","label":"Edge beam width","unit":"mm","defaultValue":300,"minimum":0,"step":10}]',
  '[{"lineKey":"concrete","bomRuleId":"concrete_volume"},{"lineKey":"trenchMesh","bomRuleId":"concrete_trench_mesh"},{"lineKey":"slabMesh","bomRuleId":"concrete_slab_mesh"},{"lineKey":"barChairs","bomRuleId":"concrete_bar_chair_boxes"}]'
),
(
  'Plasterer / Gib Fixer', 'Walls / Ceilings', 'walls-ceilings',
  '[{"lineKey":"wallBoard","description":"Wall plasterboard","category":"plasterboard","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"ceilingBoard","description":"Ceiling plasterboard","category":"plasterboard","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"cornice","description":"Cornice","category":"trim","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"externalAngle","description":"External angle beads","category":"trim","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"internalTape","description":"Internal corner tape","category":"compound","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"baseCoat","description":"Base coat buckets","category":"compound","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"topCoat","description":"Top coat buckets","category":"compound","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true}]',
  1, 1,
  '[{"id":"wallLengthM","label":"Total wall length","unit":"m","defaultValue":10,"minimum":0,"step":0.1},{"id":"ceilingHeightM","label":"Ceiling height","unit":"m","defaultValue":2.4,"minimum":0,"step":0.1},{"id":"ceilingAreaM2","label":"Ceiling area","unit":"m²","defaultValue":20,"minimum":0,"step":0.1},{"id":"externalCornerCount","label":"External corner count","unit":"qty","defaultValue":4,"minimum":0,"step":1},{"id":"internalCornerCount","label":"Internal corner count","unit":"qty","defaultValue":4,"minimum":0,"step":1}]',
  '[{"lineKey":"wallBoard","bomRuleId":"plaster_wall_board"},{"lineKey":"ceilingBoard","bomRuleId":"plaster_ceiling_board"},{"lineKey":"cornice","bomRuleId":"plaster_cornice"},{"lineKey":"externalAngle","bomRuleId":"plaster_external_angle"},{"lineKey":"internalTape","bomRuleId":"plaster_internal_tape"},{"lineKey":"baseCoat","bomRuleId":"plaster_compound_buckets"},{"lineKey":"topCoat","bomRuleId":"plaster_compound_buckets"}]'
),
(
  'Roofer', 'Corrugated / Metal', 'corrugated-metal',
  '[{"lineKey":"sheets","description":"Metal roof sheets","category":"roofing","quantity":1,"unit":"square metre","unitType":"sqm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"battens","description":"Roof battens","category":"structural","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"gutter","description":"Guttering","category":"stormwater","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"downpipes","description":"Downpipes","category":"stormwater","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"capping","description":"Ridge capping","category":"roofing","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"screws","description":"Roofing screws","category":"fixings","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true}]',
  1, 1,
  '[{"id":"pitchDegrees","label":"Roof pitch","unit":"degrees","defaultValue":22.5,"minimum":0,"maximum":88,"step":0.5},{"id":"planRoofAreaM2","label":"Plan roof area","unit":"m²","defaultValue":100,"minimum":0,"step":0.1},{"id":"gutterLengthM","label":"Total gutter length","unit":"m","defaultValue":20,"minimum":0,"step":0.1},{"id":"downpipeCount","label":"Downpipe count","unit":"qty","defaultValue":4,"minimum":0,"step":1},{"id":"ridgeCappingLengthM","label":"Ridge capping length","unit":"m","defaultValue":10,"minimum":0,"step":0.1}]',
  '[{"lineKey":"sheets","bomRuleId":"roof_sheet_area"},{"lineKey":"battens","bomRuleId":"roof_battens"},{"lineKey":"gutter","bomRuleId":"roof_gutter"},{"lineKey":"downpipes","bomRuleId":"roof_downpipes"},{"lineKey":"capping","bomRuleId":"roof_ridge_capping"},{"lineKey":"screws","bomRuleId":"roof_screws"}]'
),
(
  'Electrician', 'Rough-in / Fit-out', 'rough-in-fit-out',
  '[{"lineKey":"cable","description":"Twin and earth cable","category":"cable","quantity":1,"unit":"linear metre","unitType":"lm","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":false},{"lineKey":"drums","description":"100 m cable drums","category":"cable","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"singleFaceplates","description":"Single GPO faceplates","category":"fit-off","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"doubleFaceplates","description":"Double GPO faceplates","category":"fit-off","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"mountingBlocks","description":"GPO mounting blocks","category":"rough-in","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true},{"lineKey":"lights","description":"Light fittings","category":"fit-off","quantity":1,"unit":"each","unitType":"item","unitCost":0,"markupPercentage":20,"wastagePercentage":0,"isBulkItem":true}]',
  1, 1,
  '[{"id":"singleGpoCount","label":"Single GPO count","unit":"qty","defaultValue":4,"minimum":0,"step":1},{"id":"doubleGpoCount","label":"Double GPO count","unit":"qty","defaultValue":8,"minimum":0,"step":1},{"id":"lightFittingCount","label":"Light fitting count","unit":"qty","defaultValue":8,"minimum":0,"step":1},{"id":"averageCableRunM","label":"Average cable run per point","unit":"m","defaultValue":12,"minimum":0,"step":0.5}]',
  '[{"lineKey":"cable","bomRuleId":"electrical_cable_length"},{"lineKey":"drums","bomRuleId":"electrical_cable_drums"},{"lineKey":"singleFaceplates","bomRuleId":"electrical_single_faceplates"},{"lineKey":"doubleFaceplates","bomRuleId":"electrical_double_faceplates"},{"lineKey":"mountingBlocks","bomRuleId":"electrical_mounting_blocks"},{"lineKey":"lights","bomRuleId":"electrical_light_fittings"}]'
)
ON CONFLICT ("trade_type", "slug", "template_revision") DO NOTHING;